Accomodate getColumns() undefined responses
In upgrading the snowflake-sdk dependency from v2.2.0 to v2.3.6, we encountered a breaking change.

In v2.3.0, commit 16e3bf5 (SNOW-2341089 Modify getColumns to return undefined option (#1170)) modified the getColumns method signature to allow an optional undefined return value.

tsc fails with:

```
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts:877:56 - error TS2345: Argument of type 'Column[] | undefined' is not assignable to parameter of type 'Column[]'.
  Type 'undefined' is not assignable to type 'Column[]'.

877         const hydrationMap = this.generateHydrationMap(stmt.getColumns());
                                                           ~~~~~~~~~~~~~~~~~
```

One way to address this error is to change instances of `stmt.getColumns()` to `stmt.getColumns() ?? []`, falling back to an empty array.