Bump dependency of aws-creds to fix instance metadata
I want to bring this update of the `aws-creds` into cube:
https://github.com/durch/rust-s3/pull/139/files

I was trying to use the instance metadata to mount the remote storage from s3 using the instance metadata of the pod running in the eks cluster.

I was facing the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CubeError { message: "No credentials provided as arguments, in the environment or in the profile file. \n Json Error: expected value at line 1 column 1", backtrace: "", cause: User }', /build/cubestore/cubestore/src/config/mod.rs:848:86
stack backtrace:
   0: rust_begin_unwind
             at /rustc/71b8742bbcbed2cd908dbc031d6552d8b528c037/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/71b8742bbcbed2cd908dbc031d6552d8b528c037/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/71b8742bbcbed2cd908dbc031d6552d8b528c037/library/core/src/result.rs:1355:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: cubestored::main::{{closure}}
  12: tokio::park::thread::CachedParkThread::block_on
  13: tokio::runtime::thread_pool::ThreadPool::block_on
  14: tokio::runtime::Runtime::block_on
  15: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I was using the kube2iam for assuming roles.


Running the command:
```
curl http://169.254.169.254/latest/meta-data/iam/info
```

I got the wrong profile name (not the one assigned by the pod annotations). The subsequent call for the details return non JSON response which causes the above error.

When I use the endpoint provided in a fix the I get the correct profile name
```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials
```